### PR TITLE
Remove support below IOS11

### PR DESCRIPTION
**Pull request by Pogodenhelder**
Remove Ios 9/10 since we all know Iphone6 and higher will only be supported by Nia later in febr. it will be no point in supporting older versions.
Iphone 6 supports ios 11 so its save to remove the older ios versions.

### CODE REVIEW

**Comment by TheQL** [comment]
5s should be a valid device still.

**Comment by Pogodenhelder** [comment]
devs, please take a look at the code before merging.. im not a python programmer.

**Comment by Pogodenhelder** [comment]
im not touching devices.

**Comment by TheQL** [comment]
Sure, but we don't know yet if only 32-bit support is removed and that's Niantic's weird way of phrasing that. No proof that iOS9 or 10 won't be supported anymore, or is there?

**Comment by Pogodenhelder** [comment]
press release:

In an upcoming update to Pokémon GO, we will end support for Apple devices not capable of upgrading to iOS 11, such as iPhone 5 and iPhone 5c models. This change is a result of improvements to Pokémon GO that push the application beyond the capabilities of the operating systems on such devices. This change will take effect on 02/28/2018. After that date, Trainers using affected devices may no longer be able to access their Pokémon GO accounts from that device, or use their PokéCoins or other items in their Bags. They will need to switch to a supported device to continue playing Pokémon GO. You can see the full list of impacted devices and learn more by visiting our Help Center.

we can still add support for the 5s, but frankly why would be.. it would drop support propably in july when new ios comes out as well.
i would say, in this time, there is no need for support older ios version, just in case mr.mime emulates the device as iphone6 with ios 9 is not something you want in my opinion.
all devices that we now have are capable of ios11, so lets stick to ios11

**Comment by Pogodenhelder** [comment]
@TheQL

no there is NO proof yet.. the fact that they say they are not capable of upgrading to ios11 is the reason..
But if they are not capable, why support the ios version then.
what if Nia decides to check on device AND iosversion all of a sudden without warning?
the big red flag will wave on the workers.
Since we support ios11 capable devices, we can safely assume that we RUN ios11, then you are safe in that emulation way.

**Comment by TheQL** [comment]
It's true it does not hurt to remove it. It just reduces the randomness to a pretty low value. Add more iOS 11 incarnations at least.

**Comment by Pogodenhelder** [comment]
more versions added, those are the public release version, latest was from January 8th 2018

**Comment by Pogodenhelder** [comment]
fixed my mistake.
to clarify.. 
original code was if iphone 10 then iphone 9 then iphone 8, everything else was ios 9 and 10.
since we force everything to ios11, code must not be removed, but force the lower end models to use ios11 instead of ios9 or 10.
well hopefully i made myself clear in some matter ^^ :p

**Comment by rlodev67** [comment]
@Pogodenhelder you want to force every device to run ios11, why not; But doesn't need to check which device is it:
 if device.startswith('iPhone10'):
              ios_pool = ios11
          elif device.startswith('iPhone9'):
 -            ios_pool = ios10 + ios11
 +            ios_pool = ios11
          elif device.startswith('iPhone8'):
 -            ios_pool = ios9 + ios10 + ios11
 +            ios_pool = ios11
          else:
 -            ios_pool = ios9 + ios10
 +            ios_pool = ios11


replace by ios_pool = ios11

**Comment by Pogodenhelder** [comment]
@rlodev67 i didnt want to touch that code.. again im no python programmer, anyway removed the check

**Comment by TheQL** [comment]
It will have to be re-added with iOS12. That's no big deal. Or leave it in as it was, although it looks stupid, so a future addition of an iOS12 pool is even easier.

**Comment by TheQL** [comment]
Add 11.2.5

**Comment by Pogodenhelder** [comment]
ah i see you already added 11.2.5 👍

**Pull request merged**
