### PR TITLE
New list of COMMON Pokemon

### PR DESCRIPTION
**Pull request by tokar86a**
## Description

New list of Common Pokemon so the account can be detected if they are shadowbanned. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by TheQL** [comment]
Please follow a correct numeric sorting of Pokemon in the list and don't just add at the end. Then this can be merged.

**Comment by TheQL** [comment]
Ok, I vote to merge!

**Comment by ngovil21** [comment]
How has this been tested or is there a source for shadowbanned pokemon?

**Comment by tokar86a** [comment]
https://github.com/Hydro74000/Monocle/commit/048bb8bed90ff995d288120e31ef8e3e3710a120

**Comment by ngovil21** [comment]
Thanks, looks good to me.

**Pull request merged**
