### PR TITLE
Tokar86a shadowban 12 2 2018

### PR DESCRIPTION
**Pull request by tokar86a**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by ngovil21** [comment]
This is likely a good change, but I think we should wait until after the event to merge this.

**Comment by rlodev67** [comment]
What is your source ?

**Comment by tokar86a** [comment]
bbdoc

**Comment by tokar86a** [comment]
https://github.com/Hydro74000/Monocle/commit/92cd403d8dffab259332d08e3afa729b85242432

**Pull request merged**
